### ISSUE TITLE
New Landscape Entry - Fedora

### ISSUE THREAD

**Issue by wmat** [riscv-admin/riscv-landscape#104]
### Project Name

Fedora

### Description

Add Fedora to the Operating Systems landscape.

### Homepage URL

https://fedoraproject.org/wiki/Architectures/RISC-V

### Repo URL

https://github.com/rwmjones/fedora-riscv-bootstrap

### Organization hosting or owning the project

Fedora

### Logo

![getfedora-ar21](https://user-images.githubusercontent.com/57188/220739027-bf4507c0-bac0-4388-b079-71d77d0683dc.svg)

### Category

Stack - Operating Systems

**Comment by bprestonlf** [comment]
@wmat - Fedora has been added: https://landscape.riscv.org/

Thanks!
