### ISSUE TITLE
New Landscape Entry - openEuler

### ISSUE THREAD

**Issue by ZhengZhenyu** [riscv-admin/riscv-landscape#124]
### Project Name

openEuler

### Description

openEuler is an open source platform developed and operated by OpenAtom Foundation. Its unified and open OS supports multiple processor architectures, helping promote a more robust software and hardware ecosystem through joint efforts of the community.

openEuler has multiple release that supports RISC-V, so add openEuler to the OS category of the landscape, for more details, please check:
https://www.openeuler.org/en/download/architecture/

### Homepage URL

https://openeuler.org/

### Repo URL

https://gitee.com/openeuler

### Organization hosting or owning the project

https://www.crunchbase.com/organization/%E5%BC%80%E6%94%BE%E5%8E%9F%E5%AD%90%E5%BC%80%E6%BA%90%E5%9F%BA%E9%87%91%E4%BC%9A

### Logo

https://www.openeuler.org/img/other/brand/vertical-left.svg

### Category

Stack - Operating Systems

**Comment by ZhengZhenyu** [comment]
@bprestonlf @rpsene  Hi, any comment on this request?

**Comment by rpsene** [comment]
@ZhengZhenyu reviewing it right now.

**Comment by bprestonlf** [comment]
@ZhengZhenyu - Thank you for the submission! openEuler has been added to the landscape: https://landscape.riscv.org/

**Comment by ZhengZhenyu** [comment]
Thanks alot
