### ISSUE TITLE
New Landscape Entry - MachineWare SIM-V

### ISSUE THREAD

**Issue by aut0** [riscv-admin/riscv-landscape#138]
### Project Name

SIM-V

### Description

SIM-V is our ultra-fast, functional RISC-V instruction set simulator. It enables you to verify your RISC-V software before hardware becomes available. Its rapid simulation speed reduces test runtimes, enabling your teams to reap detailed results sooner. All the while reducing energy consumption and saving time and money.

### Homepage URL

www.machineware.de

### Repository URL

Not open-source

### Organization hosting or owning the project

MachineWare GmbH

### Evidence of RISC-V ecosystem support

I'm not sure what to put here.

### Logo

![20220213_MachineWare_Logo_Logo 2 (3)](https://user-images.githubusercontent.com/7107904/232568247-37cc1857-4e2e-4d06-b0a5-3613b1782787.svg)

### Category

Design Tools

**Comment by rpsene** [comment]
@bprestonlf this can be added as part of Design Tools + Compilers. +1

**Comment by andyjohnstonmoore** [comment]
+1
