### ISSUE TITLE
New Landscape Entry - [SERV]

### ISSUE THREAD

**Issue by olofk** [riscv-admin/riscv-landscape#139]
### Project Name

SERV

### Description

The award-winning SERV is the world's smallest RISC-V CPU

### Homepage URL

https://serv.readthedocs.io

### Repository URL

https://github.com/olofk/serv

### Organization hosting or owning the project

Olof Kindgren Enterprises

### Evidence of RISC-V ecosystem support

SERV is used in deeply embedded applications or other places where size is the primary concern. This is an area typically occupied by 8-bit CPUs such as 8051, but where it's now possible to also use RISC-V. Example applications is Fraunhofer institute using it in cranial implants and Harvard/PragmatIC Semi using it as a demonstrator for novel printed electronics. It is also used in the [CoreScore](https://corescore.store/) benchmark to calculate the number of RISC-V CPUs that can fit into various FPGA boards

### Logo

![serv](https://user-images.githubusercontent.com/2194902/232591167-18a2b57b-d59b-4bd0-8823-36d0967cc7b0.svg)

### Category

Implementations

**Comment by rpsene** [comment]
@bprestonlf this can be added as part of the Implementations category. +1

**Comment by andyjohnstonmoore** [comment]
+1
