### ISSUE TITLE
Update Landscape Entry for Canonical Ubuntu RISC_V PROJECT

### ISSUE THREAD

**Issue by feliciajia** [riscv-admin/riscv-landscape#140]
### Changes requested

Please help update the Canonical Ubuntu logo to the latest version attached and update the below information accordingly:

Name: Canonical Ubuntu (not only Ubuntu)
Repository: https://ubuntu.com/download/risc-v
LinkedIn: https://www.linkedin.com/company/canonical/
Headcount:500-1000

Thanks!

Any questions, please contact me at felicia.jia@canonical.com.

![_Canonical Ubuntu](https://user-images.githubusercontent.com/103125521/232624456-d4635737-d66d-4f35-8892-9df40af1337e.svg)

**Comment by bprestonlf** [comment]
@feliciajia - entry has been updated: https://landscape.riscv.org/

Thanks!

**Comment by feliciajia** [comment]
Perfect, thank you!FeliciaOn Apr 17, 2023, at 6:55 PM, Brett Preston ***@***.***> wrote:﻿
@feliciajia - entry has been updated: https://landscape.riscv.org/
Thanks!
