### ISSUE TITLE
Update Landscape Entry for [OpenHW Group]

### ISSUE THREAD

**Issue by DBees** [riscv-admin/riscv-landscape#142]
### Changes requested

1. Should include tag for "Open Source Hardware and Software"
2. Licenses Apache 2.0, Solderpad 2.1, EPL 2.0
3. Include description "Developing the CORE-V ecosystem of high quality open-source cores, related IP, software and tools in line with industry best practices"

4. Project repos (please list using the following table in github markdown)

| Working Group | Repo | Description |
| -------------------- | -------------------- | -------------------- | | Cores TG | [Core-v-cores roadmap](https://github.com/openhwgroup/core-v-cores) | | | | [CTG meetings and minutes](https://github.com/openhwgroup/programs/tree/master/TGs/cores-task-group)| | | | [CVA6](https://github.com/openhwgroup/cva6) | 6-stage, application-class core | | | [CVA5](https://github.com/openhwgroup/cva5) | 5-stage, FPGA-optimized application-class core | | | [CVW](https://github.com/openhwgroup/cvw) | 5-stage, application-class core with education focus | | | [CV32E40P](https://github.com/openhwgroup/cv32e40p) | 4-stage, embedded-class core implementing PULP extensions | | | [CV32E40S](https://github.com/openhwgroup/cv32e40s) | 4-stage, embedded-class core with security focus | | | [CV32E40X](https://github.com/openhwgroup/cv32e40x) | 4-stage, embedded-class core supporting X-Interface | | | [CV32E41P](https://github.com/openhwgroup/cv32e41p) | 4-stage, embedded-class core prototyping Zfinx and Zce | | | [CV32E20](https://github.com/openhwgroup/cve2) | 2-stage, embedded-class microcontroller core and core complex | | | [CV-HPDCACHE](https://github.com/openhwgroup/cv-hpdcache) | High performance L1 Data Cache | | Verification TG | [VTG meetings and minutes](https://github.com/openhwgroup/programs/tree/master/TGs/verification-task-group)| | | | [CORE-V Verif](https://github.com/openhwgroup/core-v-verif) | Common test bench for OpenHW Cores | | | [FORCE RISC-V](https://github.com/openhwgroup/force-riscv) | Advanced RISC-V instruction set generator | | | [ARVM](https://github.com/openhwgroup/advanced-riscv-verification-methodologies) | Advanced RISC-V Verification Methodologies | | Software TG | [SWTG meetings and minutes](https://github.com/openhwgroup/core-v-sw) | | | | [CORE-V GNU Tools](https://github.com/openhwgroup/corev-gcc) | GNU Tools Project for embedded-class CORE-V cores | | | [CORE-V LLVM](https://github.com/openhwgroup/corev-llvm-project) | LLVM Tools Project for embedded-class CORE-V cores | | | [CORE-V FreeRTOS Kernel](https://github.com/openhwgroup/core-v-freertos-kernel) | FreeRTOS Kernel for embedded-class CORE-V cores | | | [CORE-V FreeRTOS](https://github.com/openhwgroup/core-v-freertos) | FreeRTOS for embedded-class CORE-V cores | | | [CORE-V QEMU](https://github.com/openhwgroup/corev-qemu) | QEMU emulator for CORE-V-MCU | | | [CORE-V SDK](https://github.com/openhwgroup/core-v-sdk) | SDK and IDE for embedded-class CORE-V cores | | Hardware TG | [HWTG meetings and minutes](https://github.com/openhwgroup/programs/tree/master/TGs/hardware-task-group) | | | | [CORE-V-MCU](https://github.com/openhwgroup/core-v-mcu) | ASIC and FPGA MCU implementation of CV32E40P | | | [CORE-V-MCU-DEVKIT](https://github.com/openhwgroup/core-v-mcu-devkit) | Devkit for CORE-V-MCU | | Technical Working Group | [OpenHW project dashboard](https://github.com/openhwgroup/programs/tree/master/dashboard) | | | | [Project Description Folders](https://github.com/openhwgroup/programs/tree/master/Project-Descriptions-and-Plans) | | | | [OpenHW Project process and templates](https://github.com/openhwgroup/programs/tree/master/process) | |

@michelleclancy
@rickoco

**Comment by bprestonlf** [comment]
@DBees - Updates have been applied, based on current Landscape functionality. Future features will be opened to accommodate request(s) for:

1. New tag for Open Source Hardware
2. Permit GitHub markdown in entry descriptions
3. Allow for multiple licenses to be included on one entry

**Comment by DBees** [comment]
ok thanks @bprestonlf 
Is it really needed to apply the "NoOpenSSF Best Practices" label? That implies that open source best practices haven't been thought through - e.g. we use the Eclipse Development Process which embodies a whole swathe of best practices. Duncan
