### ISSUE TITLE
New Landscape Entry - Valtrix Systems

### ISSUE THREAD

**Issue by deepsrc** [riscv-admin/riscv-landscape#143]
### Project Name

Valtrix Systems

### Description

Valtrix Systems - an EDA company from Bangalore, India, is into the development of CPU and SoC design verification tools. STING, the flagship product of Valtrix, is a commercially supported design verification tool for RISC-V used by several CPU and SoC vendors for ensuring functional correctness and architectural compliance. The tool can be configured to generate portable bare-metal programs containing self-checking architecturally-correct test stimulus, which can then be enabled on simulation, FPGA prototypes, emulation or silicon.

### Homepage URL

https://www.valtrix.in

### Repository URL

Proprietary

### Organization hosting or owning the project

Valtrix Systems

### Evidence of RISC-V ecosystem support

https://www.prnewswire.com/in/news-releases/valtrix-and-codasip-cooperate-on-verification-of-risc-v-systems-822872272.html
https://www.prnewswire.com/in/news-releases/valtrix-broadens-support-for-risc-v-design-verification-with-latest-updates-to-sting-842621057.html
https://apnews.com/1c7def0817b4d4979641d8dd5b896fbf
https://www.ryt9.com/en/anpi/250484
https://www.valtrix.in/assets/pdf/Verifying_PULPino_RISCY_Core_for_a_Google_Accelerator_with_STING.pdf

### Logo

![Valtrix_Company_Logo_2022v1 0](https://user-images.githubusercontent.com/2525384/232651627-3aa0d149-41b9-44fb-ae22-28fd38afbe57.svg)

### Category

Design Tools

**Comment by rpsene** [comment]
@bprestonlf for this we need a new Design Verification Tools group. Let see how we can reorganize the Landscape to accommodate new groups before merging this.

**Comment by bprestonlf** [comment]
Will place in Design Tools + Compilers for now. Further refinement of categories/placement can be revisited later.

@andyjohnstonmoore - Please provide your +1 and I will merge in.

Thanks!

**Comment by andyjohnstonmoore** [comment]
+1
