### ISSUE TITLE
[Feature Request] New Landscape category: Processors

### ISSUE THREAD

**Issue by bprestonlf** [riscv-admin/riscv-landscape#149]
### Does your feature request address a specific issue? Please elaborate.

Request raised over email for a new Landscape category for Processors

### Outline your desired solution

New category for Processors

### Discuss any alternative solutions or features you've considered.

n/a

### Additional information.

Initial thought would be 1 entry per company. Point to a page that lists available RISC-V Processors.

[RISC-V Exchange](https://riscv.org/exchange/) for detailed listings?

**Comment by rpsene** [comment]
done.
