### ISSUE TITLE
[Feature Request] New Landscape category: Developer Boards

### ISSUE THREAD

**Issue by bprestonlf** [riscv-admin/riscv-landscape#150]
### Does your feature request address a specific issue? Please elaborate.

Request raised over email for a new Landscape category for Developer Boards

### Outline your desired solution

New category for Developer Boards

### Discuss any alternative solutions or features you've considered.

n/a

### Additional information.

Initial thought would be 1 entry per company. Point to a page that lists available RISC-V Developer Boards.

[RISC-V Exchange](https://riscv.org/exchange/) for detailed listings?

**Comment by rpsene** [comment]
done.
