### ISSUE TITLE
New Landscape Entry - [PROJECT]

### ISSUE THREAD

**Issue by williamelamie** [riscv-admin/riscv-landscape#156]
### Project Name

PX5 RTOS

### Description

The PX5 RTOS features a native implementation of the industry standard POSIX pthreads API as well as best-of-class size and performance. As for safety and security, the PX5 RTOS provides Pointer/Data Verification (PDV) technology, which developers can leverage at run-time to verify function return addresses, function pointers, system objects, global data, and memory pools. This technology is unique to the PX5 RTOS. In addition to the native POSIX pthread support (semaphore, mutex, message queue, etc.), the PX5 RTOS also offers real-time extensions such as event flags, fast queues, tick timers, memory management, and more. Given the PX5 RTOS industry-standard POSIX pthreads API support, a wide range of software stacks are instantly enabled – both open source and commercial – for real-time embedded IoT platforms.
 

### Homepage URL

www.px5rtos.com

### Repository URL

https://px5rtos.com/free-rtos-download-evaluations/

### Organization hosting or owning the project

PX5

### Evidence of RISC-V ecosystem support

Please find PX5 RTOS for SiFive HiFive1 board example here:
https://px5rtos.com/free-rtos-download-evaluations/ 

### Logo

![px5-rtos-logo-black](https://user-images.githubusercontent.com/116401793/234367363-1cfe7acb-b75b-47c5-99d9-0739924cf33c.png)

### Category

Operating Systems

**Comment by andyjohnstonmoore** [comment]
+1
