### ISSUE TITLE
New Landscape Entry - XtratuM

### ISSUE THREAD

**Issue by MMunozFentISS** [riscv-admin/riscv-landscape#195]
### Project Name

XtratuM Next Generation

### Description

[XtratuM Next Generation (XNG)](https://www.fentiss.com/xtratum/) is an embedded ECSS category B qualified type 1 hypervisor aimed at safe and efficient embedded real-time systems through virtualization, allowing different applications to share the same hardware platform through the isolation in time and space of these applications in partitions (TSP).
Thanks to XtratuM, developers can build bare-metal applications or use different operating systems over the same platform, as well as to allocate applications with different criticality levels to each partition.
The use of XtratuM is convenient for systems in which the main challenges deal with safety, the reuse of certified applications, dynamic software updates and size, weight, power and cost reduction of embedded safety-critical systems.

XtratuM Next Generation is currently available to be run on top of a NOEL-V processor.

### Homepage URL

https://www.fentiss.com/xtratum/

### Repository URL

NA

### Organization hosting or owning the project

FentISS

### Evidence of RISC-V ecosystem support

The results of the project DeRisc are public and can be fount in the [project web page](https://derisc-project.eu/use-cases/).

### Logo

![fentISS_logo_vectorized](https://user-images.githubusercontent.com/132041842/235096854-fda1e0fc-7f80-41af-baf9-bf0302564a53.svg)

### Category

Hypervisor

**Comment by andyjohnstonmoore** [comment]
+1

**Comment by rpsene** [comment]
+1
