### ISSUE TITLE
New Landscape Entry - LithOS

### ISSUE THREAD

**Issue by MMunozFentISS** [riscv-admin/riscv-landscape#196]
### Project Name

LithOS

### Description

[LithOS](https://www.fentiss.com/lithos/) is a real-time guest operating system specially designed for [XtratuM hypervisor](https://www.fentiss.com/xtratum/). 
LithOS is qualified for flight ECSS category B.
LithOS follows the ARINC-653 APEX standard, a software specification which ensures exclusive access to physical and temporal resources in partitioned real-time embedded systems.

Choosing LithOS as your guest OS your system will be fully integrated as a XtratuM Partition.

LithOS is currently available to be run on top of a NOEL-V processor.

### Homepage URL

https://www.fentiss.com/lithos/

### Repository URL

Not Available

### Organization hosting or owning the project

FentISS

### Evidence of RISC-V ecosystem support

The results of the project DeRisc are public and can be fount in the [project web page](https://derisc-project.eu/use-cases/).

### Logo

![](https://user-images.githubusercontent.com/132041842/235096854-fda1e0fc-7f80-41af-baf9-bf0302564a53.svg)

### Category

Operating Systems

**Comment by andyjohnstonmoore** [comment]
+1
