### ISSUE TITLE
New Landscape Entry - gem5

### ISSUE THREAD

**Issue by powerjg** [riscv-admin/riscv-landscape#216]
### Project Name

gem5

### Description

The gem5 simulator is a modular platform for computer-system architecture research, encompassing system-level architecture as well as processor microarchitecture. The gem5 project is community-led with an open governance model. The gem5 simulator was originally conceived for computer architecture research in academia, but it has grown to be used in computer system design by academia, industry for research, and in teaching. The gem5 simulator contains cycle-level models for processors, cache hierarchies, memory systems, and devices. It can boot Linux and run most application for a variety of ISAs including Arm, RISC-V, and x86.

### Homepage URL

https://www.gem5.org/

### Repository URL

https://github.com/gem5/gem5

### Organization hosting or owning the project

gem5 community

### Evidence of RISC-V ecosystem support

gem5 has full support for running applications with the RISC-V ISA and booting RISC-V Linux. gem5 has support for many RISC-V extensions including Keystone and RVV-1.0 support is actively being developed. gem5 has been used for a large number of research papers with RISC-V.

See https://github.com/gem5/gem5/tree/stable/src/arch/riscv

### Logo

![gem5](https://user-images.githubusercontent.com/109596/236890291-78dc1467-f2a7-49d8-a6e7-8c551ec380f1.svg)

### Category

Design Tools

**Comment by rpsene** [comment]
@bprestonlf +1.

**Comment by powerjg** [comment]
Thanks!
