### ISSUE TITLE
Update Landscape Entry for U-Boot

### ISSUE THREAD

**Issue by xypron** [riscv-admin/riscv-landscape#217]
### Changes requested

The source repository of the U-Boot project is https://source.denx.de/u-boot/u-boot . Github only serves as mirror.

The website https://www.denx.de/wiki/U-Boot is not maintained anymore. It forwards to https://u-boot.readthedocs.io/en/latest/ .

The overall license is GPL-2.0 (see https://source.denx.de/u-boot/u-boot/-/blob/master/Licenses/README).

Best regards

Heinrich Schuchardt
Maintainer of the UEFI sub-system in U-Boot

**Comment by bprestonlf** [comment]
@xypron - Thank you. Updates applied.
