### ISSUE TITLE
New Landscape Entry - [PULP Platform]

### ISSUE THREAD

**Issue by gurkaynak** [riscv-admin/riscv-landscape#218]
### Project Name

PULP Platform

### Description

PULP Platform has developed permissively-licensed open-source RISC-V based energy-efficient computing architectures since 2013. 

### Homepage URL

https://pulp-platform.org/

### Repository URL

https://github.com/pulp-platform

### Organization hosting or owning the project

ETH Zürich

### Evidence of RISC-V ecosystem support

PULP platform has provided many academic and industrial projects with their computing solutions. Among others, several key IPs by OpenHW group ([CVA6](https://github.com/openhwgroup/cva6), [CV32E40P](https://github.com/openhwgroup/cv32e40p)), and LowRISC ([Ibex](https://github.com/lowRISC/ibex)) trace back their origins to releases of PULP platform (the repos were transferred to the respective current owners). Commercially Greenwaves GAP8/GAP9 series of chips are based on the developments at PULP platform ((https://greenwaves-technologies.com/low-power-processor/)). 

A list of publications can be found on the following page:
https://pulp-platform.org/publications.html

### Logo

<img width="143" alt="pulp" src="https://user-images.githubusercontent.com/18549602/236892800-f8ef922d-d80f-4ec9-b163-bf4ac25efafc.png">
[eth_logo](https://user-images.githubusercontent.com/18549602/236892843-7f9a6402-8e06-4d69-8f6c-52bb8a039ad8.png)
[pulp_logo_big1.pdf](https://github.com/riscv-admin/riscv-landscape/files/11423687/pulp_logo_big1.pdf)

### Category

Implementations

**Comment by rpsene** [comment]
@bprestonlf  +1.

**Comment by bprestonlf** [comment]
+ @andyjohnstonmoore

**Comment by gurkaynak** [comment]
can you change the twitter account to: [https://twitter.com/pulp_platform ](https://twitter.com/pulp_platform )
