### ISSUE TITLE
New Landscape Entry - [MachineWare]

### ISSUE THREAD

**Issue by aut0** [riscv-admin/riscv-landscape#220]
### Project Name

MachineWare

### Description

MachineWare's virtual prototypes simulate RISC-V hardware at bit-level accuracy, shortening development time and enhancing software security, stability, and quality. 

### Homepage URL

https://www.machineware.de/

### Repository URL

https://www.machineware.de/

### Organization hosting or owning the project

MachineWare GmbH

### Evidence of RISC-V ecosystem support

MachineWare is a member of RISC-V International.
Could you list us under "Services".
It is not selectable in the dropdown menu.

### Logo

![20220213_MachineWare_Logo_Bildmarke](https://user-images.githubusercontent.com/7107904/236896948-f0cdb4d2-4f03-478c-ae59-9ae85fd5ce04.png)

### Category

Design Tools

**Comment by rpsene** [comment]
@bprestonlf +1

**Comment by bprestonlf** [comment]
@aut0 - Would you prefer we use the logo you have attached, or the logo available at https://landscape.riscv.org/card-mode?selected=machine-ware ?

**Comment by aut0** [comment]
@bprestonlf If possible we would like to use the attached logo as it is easier to recognize.

Thank you.

**Comment by andyjohnstonmoore** [comment]
+1
