### ISSUE TITLE
New Landscape Entry - Salus: Risc-V hypervisor for TEE development

### ISSUE THREAD

**Issue by rsahita** [riscv-admin/riscv-landscape#222]
### Project Name

Salus: Risc-V hypervisor for TEE development

### Description

Salus is a RISC-V 64 bit hypervisor used for TEE development. It is used to implement the TEE Security Manager (TSM) and the ABI proposed as part of the CoVE (Confidential VM Extension) proposed in the RVI AP-TEE (non-isa) Task Group. It will also be used to used to interface with any privileged ISA extensions developed as part of that TG (currently being discussed). 

### Homepage URL

https://github.com/rivosinc/salus

### Repository URL

https://github.com/rivosinc/salus

### Organization hosting or owning the project

Rivos Inc.

### Evidence of RISC-V ecosystem support

AP-TEE CoVE specification: https://github.com/riscv-non-isa/riscv-ap-tee/tree/main/specification

### Logo

SALUS

### Category

Hypervisor

**Comment by rpsene** [comment]
@bprestonlf +1.

**Comment by andyjohnstonmoore** [comment]
+1
