### ISSUE TITLE
New Landscape Entry - Buildroot

### ISSUE THREAD

**Issue by pscheie** [riscv-admin/riscv-landscape#229]
### Project Name

Buildroot

### Description

Buildroot is a make-based tool for building a Linux OS, typically for embedded use.  (I'm not a developer of Buildroot; I just use it and wanted others to know it supports RISC-V.)

### Homepage URL

buildroot.org

### Repository URL

https://buildroot.org/downloads/

### Organization hosting or owning the project

Buildroot community

### Evidence of RISC-V ecosystem support

'make list-defconfigs' shows all the boards that Buildroot supports.  The list includes RISC-V under Qemu, the VisionFive and VisionFive 2 boards, perhaps others (those were the only two I was familiar with).

### Logo

https://buildroot.org/images/logo.png

### Category

Operating Systems

**Comment by rpsene** [comment]
@bprestonlf +1 per email thread.

**Comment by bprestonlf** [comment]
+ @andyjohnstonmoore

**Comment by bprestonlf** [comment]
SVG is required for logo. Will list the name until one can be provided
