### ISSUE TITLE
Update Landscape Entry for Ventana Micro Systems

### ISSUE THREAD

**Issue by tlanier512** [riscv-admin/riscv-landscape#243]
### Changes requested

Please update the Ventana logo to the following:
https://www.ventanamicro.com/wp-content/uploads/2022/09/Ventana_Logo_BIG_v1.png
![Ventana_Logo_BIG_v1](https://user-images.githubusercontent.com/132968463/236980473-d53f62eb-ca9d-460b-8d90-871f6123bf04.png)

Here is our Twitter:
https://twitter.com/ventanamicro
@VentanaMicro

Updated Description:
Ventana is creating high performance RISC-V chiplets and IP for the data center, automotive, 5G edge, and client markets.

**Comment by bprestonlf** [comment]
@tlanier512 - Please provide logo in SVG format. AI also works (we can convert)

**Comment by tlanier512** [comment]
![ventanalogo](https://github.com/riscv-admin/riscv-landscape/assets/132968463/e75f04cd-ec56-4a48-9ba9-5eedceb645eb)

I tried again and also emailed it to info@riscv.org if it did not work.

**Comment by bprestonlf** [comment]
@tlanier512 - I'm not seeing the email into info@. Can you email me directly (brett@riscv.org) without the logo so we can start a thread there? Thanks!
