### ISSUE TITLE
New Landscape Entry - oreboot

### ISSUE THREAD

**Issue by orangecms** [riscv-admin/riscv-landscape#251]
### Project Name

oreboot

### Description

oreboot is a downstream fork of coreboot, i.e. oreboot is coreboot without 'c'.

oreboot is mostly written in Rust, with assembly where needed.

oreboot defaults to LinuxBoot payloads for a bootloader environment.

### Homepage URL

https://github.com/oreboot/oreboot/

### Repository URL

https://github.com/oreboot/oreboot/

### Organization hosting or owning the project

N/A

### Evidence of RISC-V ecosystem support

Our focus is on RISC-V at this point, the only fully supported platform as of now being the Allwinner D1.

Work is in progress on StarFive SoCs (JH7100 and JH7110 as featured on VisionFive1/2) and the Bouffalo Lab BL808 (Sipeed M1S, Pine64 Ox64, etc). See the pull requets which are getting frequent updates and the corresponding development live streams that are being archived on my YouTube channel: https://www.youtube.com/@CyReVolt

### Logo

https://github.com/oreboot/oreboot/raw/main/Documentation/img/logo-full.png

### Category

Boot

**Comment by andyjohnstonmoore** [comment]
+1

**Comment by rpsene** [comment]
@bprestonlf +1.
