### ISSUE TITLE
Update Landscape Entry for [Implementation]

### ISSUE THREAD

**Issue by allenxuepeng** [riscv-admin/riscv-landscape#261]
### Changes requested

Hi Admin, 
I am from StarFive Marketing Team. 
In the **Implementation** Entry of the Landscape, you are correct that StarFive Technology is included in the **SBC** category. 
But the company also delivered its CPU IP product of [Dubhe ](https://www.starfivetech.com/en/site/riscv-core-ip) and its SoC of [JH7110 ](https://www.starfivetech.com/en/site/soc) based on SiFive U74 quad-core last year. So please add StarFive to the Category of **IP** and **Chips**.   

Thanks, 
Allen Xue 
allen.xue@starfivetech.com

**Comment by allenxuepeng** [comment]
Hi Admin, 

In the Card Mode page, please also update the following tab: https://landscape.riscv.org/card-mode?selected=shanghai-star-five-technology-co 
The company has grown to **292** employees and has expanded its product portfolio to **IP** and **Chips**. 
You can also add the Official GitHub: https://github.com/starfive-tech/

**Comment by bprestonlf** [comment]
@rpsene , @andyjohnstonmoore - Please review/approve the additional categories. I'll start work on informational updates

**Comment by bprestonlf** [comment]
@allenxuepeng - I have updated your Crunchbase page, https://www.crunchbase.com/organization/starfive-technology, which pulled in updated employee count. Should you have additional updates to the Crunchbase page, it's fairly easy to create an account (upper right), and submit in edits.

I have also added listing for your official GitHub

**Comment by andyjohnstonmoore** [comment]
+1

**Comment by rpsene** [comment]
+1 @bprestonlf !
