### ISSUE TITLE
New Landscape Entry - Nuclei RISC-V Processor IP

### ISSUE THREAD

**Issue by nathanmanuclei** [riscv-admin/riscv-landscape#262]
### Project Name

Nuclei RISC-V Processor IP

### Description

Established in 2018, Nuclei Technology Corporation is a leading RISC-V processor IP vendor in China.
Nuclei dedicates to developing high-performance/low-power processors and their associated SoC platforms to serve the rapidly growing computing system applications worldwide.
Starting from scratch, Nuclei provides a full series of processors that can meet various markets and applications, covering 5G communication, industrial control, artificial intelligence, automotive electronics, Internet of things, storage, MCU, network security, etc. As of today, more than 150 customers have officially licensed Nucleis' processor IPs.

### Homepage URL

https://www.nucleisys.com/

### Repository URL

https://github.com/Nuclei-Software/

### Organization hosting or owning the project

Nuclei System Technology

### Evidence of RISC-V ecosystem support

We have more than 150 customers licencing our RISC-V IPs.
But most of our articles or PRs are in Chinese. Please do let me know what I can provide as evidence.
Thanks

### Logo

not able to upload
is there another way like email so that i can send to logo?

### Category

Implementations

**Comment by rpsene** [comment]
@nathanmanuclei you can drag and drop your logo here; if still not possible, maybe send an email to info@risc-v.org with the  image and the link for this GH issue.

**Comment by rpsene** [comment]
@bprestonlf overall it looks good; once we get the image we are good to go.

**Comment by bprestonlf** [comment]
+ @andyjohnstonmoore

**Comment by bprestonlf** [comment]
+ @andyjohnstonmoore

**Comment by andyjohnstonmoore** [comment]
+1
