### ISSUE TITLE
Update Landscape Entry for Tenstorrent

### ISSUE THREAD

**Issue by kdockser** [riscv-admin/riscv-landscape#283]
### Changes requested

Please add:

[Implementations](https://landscape.riscv.org/?category=implementations&grouping=category) • [Accelerators](https://landscape.riscv.org/?category=accelerators&grouping=category)
[Implementations](https://landscape.riscv.org/?category=implementations&grouping=category) • [Chips](https://landscape.riscv.org/?category=chips&grouping=category)
[Implementations](https://landscape.riscv.org/?category=implementations&grouping=category) • [IP](https://landscape.riscv.org/?category=ip&grouping=category)

**Comment by bprestonlf** [comment]
attached to https://github.com/riscv-admin/riscv-landscape/issues/276

**Comment by kdockser** [comment]
Please change the text ("Tenstorrent designs ...") to:
Tenstorrent builds AI/ML accelerators and RISC-V processors in the form of IP, chiplets, chips, and boards that are scalable from 8-wide for data centers to 2-wide for edge and embedded IoT solutions.

**Comment by andyjohnstonmoore** [comment]
+1
