### ISSUE TITLE
New Landscape Entry - PikeOS

### ISSUE THREAD

**Issue by rejsys** [riscv-admin/riscv-landscape#289]
### Project Name

PikeOS

### Description

SYSGO has announced that its real-time operating system PikeOS does now support a broad range of RISC-V based architectures. 

### Homepage URL

https://www.sysgo.com/

### Crunchbase URL (https://www.crunchbase.com/)

none

### Repository URL

proprietary

### Organization hosting or owning the project

SYSGO

### Evidence of RISC-V ecosystem support

https://www.sysgo.com/press-releases/sysgo-adds-risc-v-support-to-its-pikeos-real-time-operating-system

### Logo

https://www.sysgo.com/assets/img/logo_sysgo.svg

### Category

Operating Systems

**Comment by rpsene** [comment]
+1
we are good to go @bprestonlf !

**Comment by rejsys** [comment]
Could you please add some additional Information to the entry:

Twitter: https://twitter.com/SYSGO?s=20
LinkedIn: https://de.linkedin.com/company/sysgo-gmbh
