### ISSUE TITLE
New Landscape Entry - MINRES

### ISSUE THREAD

**Issue by staskau** [riscv-admin/riscv-landscape#290]
### Project Name

MINRES

### Description

Trustworthy Software-Driven Hardware for the Intelligent Edge.
Making modern technologies accessible to Small and Medium Enterprises (SME) allows them to leverage advances in semiconductor and deploy powerfull solutions at the edge.

### Homepage URL

https://www.minres.com/

### Crunchbase URL (https://www.crunchbase.com/)

https://www.crunchbase.com/organization/minres-technologies

### Repository URL

https://github.com/Minres

### Organization hosting or owning the project

MINRES Technologies GmbH

### Evidence of RISC-V ecosystem support

https://www.edacentrum.de/scale4edge/system/files/ct_project_news/success-story-hw-verification.pdf

### Logo

![Minres_logo](https://github.com/riscv-admin/riscv-landscape/assets/69521847/2e8dce5a-58f0-4c59-8fee-2d432656413c)

### Category

Implementations

**Comment by andyjohnstonmoore** [comment]
+1 for IP in implementations

**Comment by rpsene** [comment]
+1 
good to go @bprestonlf !

**Comment by staskau** [comment]
Thank you very much for updating the lanscape! 
Could it be possible to add MINRES also to the services section?
