### ISSUE TITLE
New Landscape Entry - RISCV-VP

### ISSUE THREAD

**Issue by saahm** [riscv-admin/riscv-landscape#292]
### Project Name

RISCV-VP

### Description

RISCV-VP is a configurable and extensible platform to build Virtual Prototypes (VP) for RISC-V using C++/SystemC and TLM. Features include support for all standard RISC-V extension for the 32 and 64 bit architecture including the M/S/U privileged architecture, advanced software debugging capabilities using a GDB interface with an optional Eclipse GUI, a HiFive1 configuration and support for graphical environment models, and support for several operating systems including RIOT, Zephyr, FreeRTOS and Linux.

The VP can be used for early Software development and verification, as well as Hardware design space exploration and prototyping on the basis of SystemC TLM 2.0. 

### Homepage URL

https://agra.informatik.uni-bremen.de/projects/risc-v/

### Crunchbase URL (https://www.crunchbase.com/)

https://www.crunchbase.com/organization/university-of-bremen-2

### Repository URL

https://github.com/agra-uni-bremen/riscv-vp

### Organization hosting or owning the project

Group of Computer Architecture, University of Bremen

### Evidence of RISC-V ecosystem support

On the [homepage](https://agra.informatik.uni-bremen.de/projects/risc-v/#pub) we host an updated list of our peer reviewed related publications, which were published in journals, conferences and workshops. Additionally, other research groups utilize our implementations in various degrees for education and lecturing, as well as research work on their own. 
We can provide more information if needed.

### Logo

[No logo available at this time]()

### Category

Design Tools

**Comment by andyjohnstonmoore** [comment]
+1

**Comment by rpsene** [comment]
+1, we are good to go @bprestonlf !
