### ISSUE TITLE
New Landscape Entry - VORTEX-CoLab

### ISSUE THREAD

**Issue by anmaped** [riscv-admin/riscv-landscape#293]
### Project Name

Polarstar

### Description

VORTEX-CoLab connects industry and academia through the experimental development of products and services from concept to market. We partner with organizations to accelerate technology transfer. Polarstar addresses the transition to microservice-based applications in the RISC-V ecosystem with its new software porting service.

### Homepage URL

https://www.vortex-colab.com

### Crunchbase URL (https://www.crunchbase.com/)

no repo

### Repository URL

no repo

### Organization hosting or owning the project

VORTEX-CoLab

### Evidence of RISC-V ecosystem support

Microservices are becoming popular in embedded systems, which were traditionally built as monolithic applications. Porting applications to the RISC-V architecture that support service-oriented architectures (SOAs) and AI accelerators is becoming increasingly necessary as these technologies gain popularity. However, this task can be complex and challenging due to resources constraints and modularization. 

The white paper addresses the question “Is the RISC-V ecosystem developed enough to support the deployment of next-generation microservices?” and describes a possible solution that enables the transition to microservice-based applications in the RISC-V ecosystem. 

To support service-oriented architectures on RISC-V architecture, a solution needs to include building Board Support Packages, porting container orchestration, and porting machine learning tools such as PyCoral for machine learning-based applications. This provides a flexible, scalable, and efficient solution for running modern service-oriented applications on RISC-V architecture, enabling the use of microservices architecture on RISC-V-based embedded systems. 

The experimental development on PolarFire SoC involved multiple technologies, such as Linux kernel, containerd, K3s, and PyCoral operating on the PolarFire SoC. 

Link to the white paper: https://landing.vortex-colab.com/download/microservices_white_paper.pdf 

### Logo

![vortex-logo](https://github.com/riscv-admin/riscv-landscape/assets/13843529/10a16af8-310f-4c05-b86f-6cc4173fe725)

### Category

Services

**Comment by andyjohnstonmoore** [comment]
Would this fit better under infrastructure? If I'm right microservices is more an infrastructure software type of thing rather than a design service?

Could you have a look at https://landscape.riscv.org/ and see what you think? I'm no expert on microservices so could easily be mistaken.

**Comment by rpsene** [comment]
@bprestonlf, VORTEX-CoLab should be under services.

**Comment by andyjohnstonmoore** [comment]
+1
