### ISSUE TITLE
New Landscape Entry - VORTEX-CoLab

### ISSUE THREAD

**Issue by anmaped** [riscv-admin/riscv-landscape#294]
### Project Name

llhsc

### Description

VORTEX-CoLab connects industry and academia through experimental development of products and services from concept to market. We partner with organizations to accelerate technology transfer. llhsc is an experimental development tool that enables the construction of customized configurations for systems running the Bao static-partitioning hypervisor and also consists of a Devicetree syntax and semantic checker. 

### Homepage URL

https://www.vortex-colab.com 

### Crunchbase URL (https://www.crunchbase.com/)

no repo

### Repository URL

no repo

### Organization hosting or owning the project

VORTEX-CoLab

### Evidence of RISC-V ecosystem support

Our approach of automatically building Devicetree specifications offers a constructive way to safely configure embedded systems using a feature model and a series of deltas applied to a master DTS. It also provides a safe and efficient method for resource allocation. 

llhsc is an experimental development tool that demonstrates its potential in constructing customized configurations for systems running the Bao static-partitioning hypervisor, targeting RISC-V, and is also a Devicetree syntax and semantic checker. 

Link to the paper: https://landing.vortex-colab.com//download/hypervisor_configurator_paper_final.pdf 

Link to the tool: https://llhsc.apps.vortex-colab.com

Link to the apps page: https://landing.vortex-colab.com

### Logo

![vortex-logo](https://github.com/riscv-admin/riscv-landscape/assets/13843529/84d97edf-df75-441a-9f1d-d148f83838a1)

### Category

Design Tools

**Comment by andyjohnstonmoore** [comment]
+1

**Comment by rpsene** [comment]
+1 @bprestonlf, we are good to go.
