### ISSUE TITLE
[Feature Request] Category for Benchmarking, Test and Verification

### ISSUE THREAD

**Issue by saahm** [riscv-admin/riscv-landscape#307]
### Does your feature request address a specific issue? Please elaborate.

While the design tools category contains simulators and supersets of such that are utilized in design verification (i.e. for hardware implementations or for functional software behavior), projects such as [riscv-tests](https://github.com/riscv-software-src/riscv-tests) and [riscv-arch-test](https://github.com/riscv-non-isa/riscv-arch-test) (previously compliance tests) can hardly be made visible to users (as they aren't applications as such, but tests). There are countless other projects (riscv-formal, various benchmarkings kits like embench-iot, symex-vp, etc.) that provide guidance for test, benchmarking and verification. Putting them into "design tools" would miss the category, as something like riscv-test is a test software that I can run in an implementation to check basic conformity with the ISA. 
Therefore, it could be very beneficial to add such a new category in order to allow all projects that aren't fitting the currently available categories to be added **and** to provide a guide towards the projects that are meant for test, verification and benchmarking of implementations and simulators/emulators.

### Outline your desired solution

Add a category that can collect the projects beloging to HW/SW verifcation, testing and benchmarking.

### Discuss any alternative solutions or features you've considered.

Alternatively, have a kind of "unsorted" category. Under which everything else can be sorted into. Thus, later on, batches of projects can be put into new categories.

**Comment by bprestonlf** [comment]
@rpsene - Can we update/expand any existing Categories to capture these?

**Comment by rpsene** [comment]
@bprestonlf sounds like we can add a subcategory under Design Tools + Compilers; We can rename it to Design, Compilers and Verification and we can add subcategories: Design, Compilers, Benchmarking, Testing, Verification.

**Comment by bprestonlf** [comment]
@rpsene - If we go the path of subcategories, will need to update/place the initial 30 entries. Perhaps start by simply expanding the Category from Design Tools + Compilers to Design, Compilers and Verification?

**Comment by rpsene** [comment]
@bprestonlf I'm good with your suggestion, specially for now that we are still populating the Landscape. We can review and refine later.
