### ISSUE TITLE
New Landscape Entry - TGC-VP

### ISSUE THREAD

**Issue by staskau** [riscv-admin/riscv-landscape#319]
### Project Name

TGC-VP

### Description

The Scale4Edge ecosystem VP using VP-VIBES peripherals.

TGC-VP is a virtual platform built around a TGC core. It allows a fast and easy entry into the world of TGC-Core-Family series. Furthermore, this system is a good starting point for building any RISC-V based VP system.

### Homepage URL

https://www.minres.com/work/tgc-vp/

### Crunchbase URL (https://www.crunchbase.com/)

https://www.crunchbase.com/organization/minres-technologies

### Repository URL (Only if publicly available)

https://github.com/Minres/TGC-VP

### Organization hosting or owning the project

MINRES Technologies GmbH

### Evidence of RISC-V ecosystem support

https://www.edacentrum.de/scale4edge/system/files/ct_project_news/success-story-hw-verification.pdf

### Logo

![TGC_VP](https://github.com/riscv-admin/riscv-landscape/assets/69521847/ebff18cb-eae9-4bf3-a70c-dffc89ad06c5)

### Sub-Category

None

**Comment by rpsene** [comment]
@bprestonlf +1

**Comment by rpsene** [comment]
under Design Tools + Compilers

**Comment by andyjohnstonmoore** [comment]
+1

**Comment by bprestonlf** [comment]
https://autocrop.cncf.io/ having issues with SVG provided. Added using text-based SVG. Can update later with new SVG
