### ISSUE TITLE
New Landscape Entry - Renesas Electronics

### ISSUE THREAD

**Issue by GiPa-renesas** [riscv-admin/riscv-landscape#320]
### Project Name

Renesas RISC-V 32 & 64-Bit MCUs and MPUs

### Description

Implementing commercial products including CPUs based on the RISC-V architecture enables Renesas to provide an additional degree of choice to customers and foster innovation across many industries. Renesas' adoption of RISC-V’s open source platform allows customers the flexibility and choice to work on the platform that best suits their designs. Whether it’s general purpose MPUs or application-specific MCUs, Renesas provides the same trusted world-class reliability, ecosystem, and support to these RISC-V portfolios of products.

Renesas leads the market introduction of RISC-V based 32-bit microcontroller products with a series of ASSPs dedicated to specific target markets. A few application areas include motor control, voice-driven human-machine interface, industrial control, mixed-signal and IoT.

The ASSP EASY group benefits from the strong cooperation with an extensive network of partners to deliver the promise of a cost-effective, efficient, application-focused solutions portfolio.

Renesas' RZ Family of microprocessors also offers a RZ/Five microprocessor which includes a RISC-V CPU core.

### Homepage URL

www.renesas.com/risc-v

### Crunchbase URL (https://www.crunchbase.com/)

N/A

### Repository URL (Only if publicly available)

www.renesas.com/risc-v

### Organization hosting or owning the project

Renesas Electronics

### Evidence of RISC-V ecosystem support

Renesas Selects Andes RISC-V 32-Bit CPU Cores for its First RISC-V Implementation of ASSPs
https://www.renesas.com/eu/en/about/press-center/news/2020/news20201001.html

Renesas Extends Leading RISC-V Embedded Processing Portfolio with New Motor Control ASSP Solution
https://www.renesas.com/eu/en/about/press-room/renesas-extends-leading-risc-v-embedded-processing-portfolio-new-motor-control-assp-solution

Renesas Expands RISC-V Embedded Processing Portfolio with New Voice-Control ASSP Solution
https://www.renesas.com/eu/en/about/press-room/renesas-expands-risc-v-embedded-processing-portfolio-new-voice-control-assp-solution

Renesas Pioneers RISC-V Technology With RZ/Five General-Purpose MPUs Based on 64-Bit RISC-V CPU Core
https://www.renesas.com/eu/en/about/press-room/renesas-pioneers-risc-v-technology-rzfive-general-purpose-mpus-based-64-bit-risc-v-cpu-core

### Logo

renesas_logomark.eps
(attached below as zip file)

### Category

Implementations

### Sub-Category

Implementations -> Chips

**Comment by rpsene** [comment]
@bprestonlf +1

**Comment by andyjohnstonmoore** [comment]
+1

**Comment by GiPa-renesas** [comment]
Hello, let me attach the .eps logo as zip file, perhaps easier to handle instead of the link above.
Can you please convert it to svg, thank you.
[renesas_logomark.zip](https://github.com/riscv-admin/riscv-landscape/files/11485824/renesas_logomark.zip)
