### ISSUE TITLE
New Landscape Entry - Terapines

### ISSUE THREAD

**Issue by dodohack** [riscv-admin/riscv-landscape#337]
### Project Name

Terapines

### Description

Terapines is a HW/SW co-design toolchain provider for RISC-V based processors.

### Homepage URL

https://www.terapines.com

### Crunchbase URL (https://www.crunchbase.com/)

https://www.crunchbase.com/organization/terapines-technology

### Repository URL (Only if publicly available)

https://github.com/THU-DSP-LAB/llvm-project

### Organization hosting or owning the project

Terapines Technology (Wuhan) Co., Ltd

### Evidence of RISC-V ecosystem support

We have made significate progress in providing RISC-V SDK and compiler support for industry and open source community. 

We will have an industry talks at RISC-V Summit Europe 2023 on Wednesday.
15:15 - Hualin Wu, Terapines Ltd - Accelerate HPC and AI applications with RVV auto vectorization
https://riscv-europe.org/conference.html

We are also the compiler provider of the RISC-V based open source Ventus GPGPU, the compiler code base can be found at https://github.com/THU-DSP-LAB/llvm-project.

We also have made several talks in RISC-V Summit China 2021, 2022 and various events in China, such as:
https://www.bilibili.com/video/BV1cB4y137bw
https://www.bilibili.com/video/BV13D4y1q72Y
https://www.bilibili.com/video/BV1V24y1p7Sq
https://www.bilibili.com/video/BV1u8411T7qj

### Logo

![Terapines_兆松科技](https://github.com/riscv-admin/riscv-landscape/assets/19568348/4af8fb13-720b-47be-a104-a64e41e4d103)

### Category

Compilers

### Sub-Category

None

**Comment by andyjohnstonmoore** [comment]
+1
