### ISSUE TITLE
[Feature Request] New implementations subcategory

### ISSUE THREAD

**Issue by ilciko** [riscv-admin/riscv-landscape#382]
### Does your feature request address a specific issue? Please elaborate.

    Additional suggestion for Section: implementations
Could be added a new subsection to better describe a complete solution provided?
        name: HPC Systems

### Outline your desired solution

  - category:
    name: Implementations
    subcategories:
      - subcategory:
        name: IP
...
      - subcategory:
        name: Single Board Computers
...
      - subcategory:
        name: Accelerators
...
      - subcategory:
        name: Chips + Processors
...
      - subcategory:
        name: HPC Systems
...

**Comment by rpsene** [comment]
Done, https://github.com/riscv-admin/riscv-landscape/commit/a674cd48b426ff36d9548bc5cf82a284a650ed43. Once we start receiving requests targeting the category we can add them in the Landscape correctly.
