### ISSUE TITLE
New Landscape Entry - AIRISC

### ISSUE THREAD

**Issue by crolfes** [riscv-admin/riscv-landscape#440]
### Project Name

AIRISC

### Description

[![MARCHID](https://img.shields.io/badge/RISC--V%20Architecture%20ID-31-000000.svg?longCache=true&style=flat-square&colorA=273274&colorB=fbb517)](https://github.com/riscv/riscv-isa-manual/blob/master/marchid.md)

The AIRISC family of RISC-V cores developed by Fraunhofer IMS enables efficient machine learning and AI in sensors, IoT devices, and other embedded applications. AIRISC variants with extended safety mechanisms such as dual-core lock-stepping (DCLS) or error correcting codes (ECC) are available for use in fail-safe systems according to ISO 26262 (up to ASIL-D) and DIN 61508.   
The AIRISC Core Complex is based on a 32-bit RISC-V CPU compatible to the RISC-V unprivileged and privileged specifications also supporting the RISC-V External Debug specification. The CPU implements a Harvard architecture with a four-level pipeline and separate AHB-Lite interfaces for instruction fetch and data access. The core's _RV32I_Zicsr_ base ISA can be further extended via a unified co-processor interface (PCPI).

### Homepage URL

www.airisc.de

### Crunchbase URL (https://www.crunchbase.com/)

https://www.crunchbase.com/organization/fraunhofer-verbund-mikroeleketronik  (Fraunhofer IMS has no single entry yet, but is part of the microelectronics alliance)

### Repository URL (Only if publicly available)

https://github.com/Fraunhofer-IMS/airisc_core_complex

### Organization hosting or owning the project

Fraunhofer Institute for Microelectronic Circuits and Systems IMS

### Evidence of RISC-V ecosystem support

Website with links to Fraunhofer RISC-V research projects.
https://www.ims.fraunhofer.de/en/Core-Competence/Smart-Sensor-Systems/Integrated-Sensor-Systems/airisc-family.html

RISC-V Ambassador Alexander Stanitzki (Fraunhofer IMS employee)

### Logo

![AIRISC_Logo_15 04_small](https://github.com/riscv-admin/riscv-landscape/assets/11528836/7e3fe05f-dfb2-4566-9bd1-d7a3594ddaa4)

https://raw.githubusercontent.com/Fraunhofer-IMS/airisc_core_complex/main/doc/gfx/logo-airisc.png

### Category

Processors

### Sub-Category

Implementations -> IP

**Comment by andyjohnstonmoore** [comment]
@bprestonlf  +1

**Comment by crolfes** [comment]
Can you please also add AIRISC to [Chips + Processors](https://landscape.riscv.org/card-mode?category=chips-processors&grouping=category), because it is a 32-bit processor and we offer several ASIC implementations.

**Comment by rpsene** [comment]
@bprestonlf +1

**Comment by bprestonlf** [comment]
@crolfes - Updated. Thanks!
