### ISSUE TITLE
[Feature Request] - Description

### ISSUE THREAD

**Issue by bprestonlf** [riscv-admin/riscv-landscape#49]
**Is your feature request related to a problem? Please describe.**
Please remove "Greyed logos are not open source." from instructions atop https://landscape.riscv.org/

**Describe the solution you'd like**
remove "Greyed logos are not open source"

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by rpsene** [comment]
Fixed by https://github.com/riscv-admin/riscv-landscape/commit/5f6e7d847918c1fc2af95fcd1d9628488291d331
