### ISSUE TITLE
[Feature Request] - Card/featured event update

### ISSUE THREAD

**Issue by bprestonlf** [riscv-admin/riscv-landscape#50]
**Is your feature request related to a problem? Please describe.**
Card, lower left, is out of date (2022 RV Summit)

**Describe the solution you'd like**
Update the card

**Describe alternatives you've considered**
Remove the card altogether

**Additional context**
Please provide specs needed for replacement image (e.g. file format - png, svg, etc. along with preferred image sizing)

**Comment by rpsene** [comment]
I bet you updated it.
