### ISSUE TITLE
[Feature Request] - Update README

### ISSUE THREAD

**Issue by bprestonlf** [riscv-admin/riscv-landscape#51]
**Is your feature request related to a problem? Please describe.**
https://github.com/riscv-admin/riscv-landscape#new-entries copied over from other project/template. Needs to be reviewed and made applicable to RISC-V's target for the Landscape

**Describe the solution you'd like**
Team review with options for further updates based on community input

**Describe alternatives you've considered**
N/A

**Additional context**
Adding here for tracking

**Comment by rpsene** [comment]
Fixed by https://github.com/riscv-admin/riscv-landscape/commit/7267d8bfc340b39f05046549bc137498a8f1839b
