### ISSUE TITLE
New Landscape Entry - Syntacore

### ISSUE THREAD

**Issue by dmsh11** [riscv-admin/riscv-landscape#539]
### Project Name

Syntacore

### Description

Syntacore is a RISC-V processor IP specialist. We create flexible, highly-efficient microprocessor cores that help customers to design unique solutions for the IoT, data storage and processing, embedded systems, cognitive, machine learning and artificial intelligence applications.

### Homepage URL

https://syntacore.com/

### Crunchbase URL (https://www.crunchbase.com/)

https://www.crunchbase.com/organization/syntacore

### Organization hosting or owning the project

Syntacore

### Evidence of RISC-V ecosystem support

https://github.com/llvm/llvm-project/pull/65599, https://github.com/llvm/llvm-project/pull/67334
•	fixed a bug with excessively long compilation for extractelement/insertelement, which occurred when RVV was disabled
debugger (OpenOCD)
•	updated the debug specification with a mechanism for decoding system register values - https://github.com/riscv/riscv-debug-spec/pull/858
•	implemented support for inaccessible registers
•	implemented Sv57 (and Sv57x4) translation mode - https://github.com/riscv/riscv-openocd/pull/904
runtimes
•	backported MD5 to jdk17 and jdk21 - https://github.com/openjdk/jdk21u/pull/209, https://github.com/openjdk/jdk17u-dev/pull/1850
•	OpenJDK: implemented several mathematical intrinsics: ceil, floor, rint, umulhi - https://github.com/openjdk/jdk/pull/15558, https://github.com/openjdk/jdk/pull/14991

### Logo

![syntacore-horizontallogo](https://github.com/riscv-admin/riscv-landscape/assets/138205785/4555796f-f6de-4020-8e78-7b58ab49bdea)

### Category

Processors

### Sub-Category

Implementations -> IP

**Comment by rpsene** [comment]
@bprestonlf +1.

**Comment by andyjohnstonmoore** [comment]
@bprestonlf +1
