### ISSUE TITLE
ZAYA Secure OS

### ISSUE THREAD

**Issue by zaya-mc** [riscv-admin/riscv-landscape#574]
### Project Name

ZAYA Secure OS

### Description

As an official RISC-V Strategic Partner, we specialise in delivering secure and robust software solutions tailored for RISC-V architecture. Our offerings include the RISC-V Security Monitor, Trusted Execution Environments (TEE), and Hypervisors designed for RISC-V powered Microcontrollers.

ZAYA Secure OS plays an important role in transforming RISC-V Microcontrollers into secure devices, particularly for those lacking built-in hardware security features.

### Homepage URL

https://www.zayatech.com/

### Crunchbase URL (https://www.crunchbase.com/)

NA

### Repository URL (Only if publicly available)

NA

### Organization hosting or owning the project

NA

### Evidence of RISC-V ecosystem support

Please see our RISC-V Solutions Page
https://www.zayatech.com/risc-v

Please see our Press Releases
https://www.za-ya.co/post/pr-zaya-now-supports-riscv
https://www.za-ya.co/post/pr-zaya-now-offers-tee-for-risc-v
https://www.za-ya.co/post/pr-zaya-secure-containers-for-risc-v

See RISC-V partner Press Releases
https://www.zayatech.com/post/zaya-and-andes-technology-offer-certifiable-tee-security-for-risc-v-based-systems
https://www.zayatech.com/post/blaitek-and-zaya-achieve-psa-level-1-certification

### Logo

![LogoColorTextRight](https://github.com/riscv-admin/riscv-landscape/assets/23231103/8f18a6c4-b859-4391-ab46-612262f8baf1)

### Category

Operating Systems

### Sub-Category

None

**Comment by andyjohnstonmoore** [comment]
+1. Might suggest change 
"tailored for RISC-V architecture"
to 
"tailored for the RISC-V architecture

**Comment by zaya-mc** [comment]
> +1. Might suggest change "tailored for RISC-V architecture" to "tailored for the RISC-V architecture

@andyjohnstonmoore ok for us, thank you

**Comment by rpsene** [comment]
@bprestonlf +1
