### ISSUE TITLE
ZAYA Hypervisor and Containerisation for MMU-Less RISC-V Microcontrollers

### ISSUE THREAD

**Issue by zaya-mc** [riscv-admin/riscv-landscape#575]
### Project Name

ZAYA Hypervisor

### Description

Containerisation enables operating system-level virtualisation for running multiple identical or diverse executions. Each container functions as an isolated environment that runs independent executables, including native applications, background services (microservices), and even complete operating systems, thanks to virtualisation.

​ZAYA brings containerisation technology to (MMU-less) RISC-V microcontrollers and embedded systems, called microcontainers.

### Homepage URL

www.zayatech.com

### Crunchbase URL (https://www.crunchbase.com/)

NA

### Organization hosting or owning the project

NA

### Evidence of RISC-V ecosystem support

Please see our RISC-V Solutions Page
https://www.zayatech.com/microcontainers
https://www.zayatech.com/risc-v

Please see our Press Releases
https://www.za-ya.co/post/pr-zaya-now-supports-riscv
https://www.za-ya.co/post/pr-zaya-now-offers-tee-for-risc-v
https://www.za-ya.co/post/pr-zaya-secure-containers-for-risc-v

See RISC-V partner Press Releases
https://www.zayatech.com/post/zaya-and-andes-technology-offer-certifiable-tee-security-for-risc-v-based-systems
https://www.zayatech.com/post/blaitek-and-zaya-achieve-psa-level-1-certification

### Logo

![LogoColorTextRight](https://github.com/riscv-admin/riscv-landscape/assets/23231103/cd093ff0-cecf-429a-ac72-53b7a03ed8ce)

### Category

Hypervisor

### Sub-Category

None

**Comment by andyjohnstonmoore** [comment]
+1

**Comment by rpsene** [comment]
@bprestonlf +1
