### ISSUE TITLE
New Landscape Entry - Emproof

### ISSUE THREAD

**Issue by nils1603** [riscv-admin/riscv-landscape#584]
### Project Name

Emproof

### Description

Agile, robust and cost-effective security and IP integrity for embedded software.

### Homepage URL

https://www.emproof.com

### Crunchbase URL (https://www.crunchbase.com/)

https://www.crunchbase.com/organization/emproof

### Organization hosting or owning the project

Emproof

### Evidence of RISC-V ecosystem support

RISC-V International Member: [Link](https://www.emproof.com/news-events/emproof-becomes-risc-v-international-member/)

[Use Case](https://www.emproof.com/sectors/semiconductors/riscv/)

### Logo

![Emproof logo](https://github.com/riscv-admin/riscv-landscape/assets/13201750/462e6999-3be1-43d4-8620-943ce43501b3)

### Category

Services

### Sub-Category

None

**Comment by rpsene** [comment]
@bprestonlf +1

**Comment by andyjohnstonmoore** [comment]
@bprestonlf +1
