### ISSUE TITLE
New Landscape Entry - INCORE

### ISSUE THREAD

**Issue by wickedb** [riscv-admin/riscv-landscape#618]
### Project Name

Incore Semiconductors 

### Description

Incore Semiconductors is a fabless core IP & chip design startup building fully customizable RISC-V cores and SoCs, to create high-performance, low-power, and cost-effective solutions for a variety of embedded applications. The founding team at InCore was previously responsible for the creation of Shakti - India’s first indigenously designed microprocessor (built on RISC-V), at the RISE lab at IIT Madras. Our CTO Neel Gala is the co-chair of the RISC-V compliance committee.

### Homepage URL

https://incoresemi.com/

### Crunchbase URL (https://www.crunchbase.com/)

https://www.crunchbase.com/organization/incore-semiconductors

### Repository URL (Only if publicly available)

https://github.com/incoresemi

### Organization hosting or owning the project

Incore Semiconductors

### Evidence of RISC-V ecosystem support

https://riscv.org/member/incore-semiconductors/
[Riscof - A Risc-V Compliance Framework and More](https://www.youtube.com/watch?v=VIW1or1Oubo)

### Logo

![incoresemi_logo](https://github.com/riscv-admin/riscv-landscape/assets/72983224/25560068-5bc5-4a25-83ec-cc40b9054ccd)

### Category

Processors

### Sub-Category

Implementations -> IP

**Comment by rpsene** [comment]
@bprestonlf +1.

**Comment by andyjohnstonmoore** [comment]
@bprestonlf +1
