### ISSUE TITLE
Update Landscape Entry for [INCORE]

### ISSUE THREAD

**Issue by govardhnn** [riscv-admin/riscv-landscape#621]
### Changes requested

Alongside Implementations - IP, 
Please add:
[Implementations - Accelerators](https://landscape.riscv.org/card-mode?category=accelerators&grouping=category)
[Implementations - Chips](https://landscape.riscv.org/card-mode?category=chips-processors&grouping=category)

References:
 - [https://riscv.org/member/incore-semiconductors/](https://riscv.org/member/incore-semiconductors/)
 
 - [Our Listings of Accelerators and Chips on the Design Linked Incentive Scheme, Ministry of Electronics and Information Technology, Government of India](https://chips-dli.gov.in/DLI/IpPortFolio2)

**Comment by bprestonlf** [comment]
@rpsene and @andyjohnstonmoore - please review additional categories requested // comment in
