### ISSUE TITLE
New Landscape Entry - NOEL-V

### ISSUE THREAD

**Issue by fabio-malatesta** [riscv-admin/riscv-landscape#663]
### Project Name

NOEL-V

### Description

We are a world leader in embedded computer systems for harsh environments. Our personnel have extended design experience, and have been involved in establishing European standards for ASIC and FPGA development. We have a long experience in the management of ASIC development projects, and in the design of flight-quality microelectronic devices. We provide IP cores and supporting development tools for embedded processors based on the SPARC and RISC-V architectures

### Homepage URL

www.gaisler.com

### Crunchbase URL (https://www.crunchbase.com/)

N/A

### Organization hosting or owning the project

Frontgrade Gaisler

### Evidence of RISC-V ecosystem support

https://www.gaisler.com/index.php/products/processors/noel-v

https://www.gaisler.com/index.php/downloads/grlib

### Logo

![Gaisler_Stacked_Dark on transparent_approved](https://github.com/riscv-admin/riscv-landscape/assets/87370661/21904dff-cc8c-48bc-b0e5-379fe85611b0)

### Category

Processors

### Sub-Category

Implementations -> IP

**Comment by rpsene** [comment]
@bprestonlf +1.
